In [3]:
import tensorflow as tf
import numpy as np

In [27]:
emb_encoder=a1
print(emb_encoder.shape.as_list())


encoder_outputs=[emb_encoder]
PAD_emb=tf.nn.embedding_lookup(emb,[1])

for enc_layer in range(6):
    with tf.variable_scope("encoder_%d"%enc_layer):
        emb_encoder=tf.pad(emb_encoder,paddings=[[0,0],[1,1],[0,0]],constant_values=PAD_emb)
        print(emb_encoder.shape.as_list())
        encoder_shape=emb_encoder.shape.as_list()

        emb_encoder=tf.reshape(emb_encoder,shape=[encoder_shape[0],encoder_shape[1],encoder_shape[2],1])# batch_size,seq_len,emb_dim,1

        filtersize=[3,10,1,20]
        filter=tf.Variable(initial_value=tf.truncated_normal(filtersize,stddev=0.01),name="filter")
        
        emb_encoder=tf.nn.conv2d(emb_encoder,filter=filter,strides=[1,1,1,1],padding="VALID",dilations=[1,1,1,1])
        emb_encoder=tf.reshape(emb_encoder,shape=[6,-1,10*2])
        A,B=tf.split(emb_encoder,2,axis=2)
        attn=tf.multiply(A,tf.nn.softmax(B))

        print(attn.shape.as_list())

        emb_encoder=attn+encoder_outputs[-1]
        a=tf.nn.softmax(emb_encoder,axis=1)
        print("a",a.shape.as_list())
        encoder_outputs.append(emb_encoder)
        print(emb_encoder.shape.as_list())



[6, 80, 10]
[6, 82, 10]
[6, 80, 10]
a [6, 80, 10]
[6, 80, 10]
[6, 82, 10]
[6, 80, 10]
a [6, 80, 10]
[6, 80, 10]
[6, 82, 10]
[6, 80, 10]
a [6, 80, 10]
[6, 80, 10]
[6, 82, 10]
[6, 80, 10]
a [6, 80, 10]
[6, 80, 10]
[6, 82, 10]


[6, 80, 10]
a [6, 80, 10]
[6, 80, 10]
[6, 82, 10]
[6, 80, 10]
a [6, 80, 10]
[6, 80, 10]


In [6]:
a=np.array(range(48))
a=a.reshape([6,8])
a=tf.constant(a,dtype=tf.float32)
b=tf.constant([1,0,1,1,0,0],dtype=tf.float32,shape=[6,1])
g=tf.constant([[1,0,1,1,0,0],[1,0,1,1,0,0]],dtype=tf.float32,shape=[2,6])

c=tf.multiply(b,a)
init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
d,f=sess.run([c,tf.nn.l2_normalize(g,1)])
print(d)
print(f)

[[  0.   1.   2.   3.   4.   5.   6.   7.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [ 16.  17.  18.  19.  20.  21.  22.  23.]
 [ 24.  25.  26.  27.  28.  29.  30.  31.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]]
[[ 0.57735026  0.          0.57735026  0.57735026  0.          0.        ]
 [ 0.57735026  0.          0.57735026  0.57735026  0.          0.        ]]


In [10]:
import tensorflow as tf 
a = tf.constant(1)
n = tf.constant(10)

def cond(a, n):
    return  a< n
def body(a,n):
    a = a + 1
    return a,n

a, n = tf.while_loop(cond, body, [a, n])
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    res = sess.run([a,n])
    print(res)


[10, 10]


In [1]:
import gym
env = gym.make('CartPole-v0')
observation = env.reset()
print(observation)
env.render()
env.step()


[ 0.0278181  -0.0079008  -0.02868299  0.00018432]


TypeError: step() missing 1 required positional argument: 'action'